### ISSUE TITLE
[templating] About html template

### ISSUE THREAD

**Issue by yunge** [SuaveIO/suave#141]
I tried "Suave.Razor", but as it's based on RazorEngine project, it doesn't support some key features such as RenderPage.

A decent html template lib is really important for real projects, so I wish Suave would provide it, maybe Razor, even something else like Mustache, just make it out of the box, thanks.

**Comment by haf** [comment]
@matthid I see ;). Beware that we're also building on mono. Here's the very simple code [we got](https://github.com/SuaveIO/suave/blob/master/src/Suave.Razor/Library.fs#L43) - I haven't used Razor much myself; perhaps you could have a look at see if we're doing it the right way?

**Comment by matthid** [comment]
RazorEngine works fine on mono (building and running), but you should upgrade to 3.5.0. After upgrading I would recommend reading [this](https://antaris.github.io/RazorEngine/Upgrading.html).

I would also recommend using a private static instance of `IRazorEngineService` or `ITemplateService` (pre 3.5.0) instead of the static `Razor` class or the new `Engine.Razor` instance. This way you can safeguard against invalid configuration of the user (if users of your library use RazorEngine as well) and you can configure your instance however you need.

I can't see any obvious pitfalls with your code. Do you have any problems with it? Like mentioned in the linked issue the `RenderPage` functionality is not missing, it is called `Include` in RazorEngine.
If you need/want to provide MVC specific syntax please read [this](https://antaris.github.io/RazorEngine/TemplateBasics.html#Extending-the-template-Syntax).
