### ISSUE TITLE
PathScan with disjointed string not working

### ISSUE THREAD

**Issue by ckpearson** [SuaveIO/suave#281]
I have the following code:

`pathScan ("/" + someItemName + "/%d") (fun x -> ....)`

And on the `"%d"` I'm getting the following:

> "The type 'string' is not compatible with the type 'PrintfFormat<'a,'b,'c,'d,'e>'"

Is this a limitation, or am I doing something wrong?

**Comment by ckpearson** [comment]
I managed to get it to work by building the `PrintfFormat` manually:

`pathScan (PrintfFormat<_,_,_,_, int>("/" + partName + "/%d")) (fun x -> OK(x.ToString()))`

Any idea if this is necessary / perhaps there's a way to add better support for this into Suave (if it's not there already)

**Comment by haf** [comment]
It's a F# limitation, similar what `sprintf` would behave like if you gave it the same input. Non-concatenated strings are compile-time constants, while strings with a runtime-dependent value in them are not. In order to prove that the `someItemName` has a constant value; either the compiler needs to statically resolve it, or if it can't, do runtime value analysis to prove that it can only ever have a single value. That said, the F# compiler does neither and only works with compile-time constants.
