### ISSUE TITLE
[OWIN] WebSocket support and OWIN

### ISSUE THREAD

**Issue by buybackoff** [SuaveIO/suave#299]
Today's news about OWIN support is great. I was struggling with self-hosted SignalR or OWIN-based WebSockets. Does Suave require Windows8 or [other support](http://owin.org/spec/extensions/owin-WebSocket-Extension-v0.4.0.htm) from underlying host to use WebSocket, or Suave does implement WebSockets itself? Is Suave closer to Kestrel, or to some wrapper over System.Web or HttpListener?

Looking in the code, I see that the only dependency on System.Web is `HttpUtility`. Could you, please, confirm that WebSockets in Suave could/should work on Windows 7 and Mono? I do not see this written explicitly in the docs.

**Comment by haf** [comment]
Suave has a self-contained WebSockets implementation that works cross-platform without dependencies on Http.sys or httpacl or the IIS infra.

However, we haven't implemented OWIN extensions, such as WebSockets over-OWIN.

**Comment by buybackoff** [comment]
But given that Suave has control over the underlying TCP connection, I believe it is possible to upgrade to an opaque stream and to WebSockets? 

I experimented with HttpListener on Win7, trying to read from Request.Stream, but it is fixed size and obviously not supported. In Suave, there is a place when a stream is [copied to a memory stream](https://github.com/SuaveIO/suave/blob/feature/owin/src/Suave/Owin.fs#L430), probably this results in the same behavior?

I need this feature very much and could start working on it if you show how to get the opaque stream? Actually, the new WebSockets middleware from aspnet could be used when opaque streams are supported (this is how they support WS and http v2 in Kestrel).

**Comment by haf** [comment]
Hi @buybackoff yes it should. Here's the hand-shake that upgrades it: https://github.com/SuaveIO/suave/blob/feature/owin/src/Suave/WebSocket.fs#L25 – do note that you could just chain an ordinary suave web socket after your validation code: https://github.com/SuaveIO/suave/blob/feature/owin/examples/WebSocket/Program.fs#L20-L42

Here's the TODO you mention; https://github.com/SuaveIO/suave/blob/feature/owin/src/Suave/Owin.fs#L535-L538 – supporting opaque streams. It includes how to get to the opaque stream. You can also see the code that deals with the buffered code: https://github.com/SuaveIO/suave/blob/feature/owin/src/Suave/Owin.fs#L687-L711 - you can control "the stream" fully in the SocketOp. It's not a stream per-say, but you can write things using the AsyncSocket module: https://github.com/SuaveIO/suave/blob/feature/owin/src/Suave/Sockets/AsyncSocket.fs

The thing is that the trigger to the stream to start writing is to write to the body. You'd need to have a stream signal back to the implementation, for which you'd probably need to delegate to an inner stream. I avoided it because I don't like typing much, but I've now typed it out:

``` fsharp
type StreamCoDispose(resources : IDisposable list, stream : Stream) =
  inherit Stream()

  override x.BeginRead(buffer, offset, count, callback, state) =
    stream.BeginRead(buffer, offset, count, callback, state)
  override x.EndRead ar =
    stream.EndRead ar
  override x.BeginWrite(buffer, offset, count, callback, state) =
    stream.BeginWrite(buffer, offset, count, callback, state)
  override x.EndWrite ar =
    stream.EndWrite ar
  override x.CanRead =
    stream.CanRead
  override x.CanSeek =
    stream.CanSeek
  override x.CanTimeout =
    stream.CanTimeout
  override x.CanWrite =
    stream.CanWrite
  override x.Close() =
    stream.Close()
  override x.CopyToAsync(other, bufferSize, ct) =
    stream.CopyToAsync(other, bufferSize, ct)
  override x.Flush() =
    stream.Flush()
  override x.FlushAsync ct =
    stream.FlushAsync(ct)
  override x.Read(buffer, offset, size) =
    stream.Read(buffer, offset, size)
  override x.ReadAsync(buffer, offset, size, ct) =
    stream.ReadAsync(buffer, offset, size, ct)
  override x.ReadByte() =
    stream.ReadByte()
  override x.ReadTimeout
    with get() = stream.ReadTimeout
    and set t = stream.ReadTimeout <- t
  override x.Seek(offset, dir) =
    stream.Seek(offset, dir)
  override x.SetLength l =
    stream.SetLength l
  override x.Length =
    stream.Length
  override x.Position
    with get() = stream.Position
    and set p = stream.Position <- p
  override x.Write(buffer, offset, size) =
    stream.Write(buffer, offset, size)
  override x.WriteAsync(buffer, offset, size, ct) =
    stream.WriteAsync(buffer, offset, size, ct)
  override x.WriteByte b =
    stream.WriteByte b
  override x.WriteTimeout
    with get() = stream.WriteTimeout
    and set t = stream.WriteTimeout <- t

  interface IDisposable with
    member x.Dispose() =
      stream.Dispose()
      List.foldBack (fun (x : IDisposable) _ -> x.Dispose()) resources ()
```

You'll need to create a stream implementation that reads/writes into a live SocketOp.

The rest of the Nancy example shows how you fetch the values from the dictionary. It should be fairly easy to create another OpaqueStream dictionary for this OWIN extension.

**Comment by buybackoff** [comment]
@haf  Thank you very much for the detailed explanation! Unfortunately I hadn't have a chance to start after the initial look into the code, and couldn't dig into this until the end of the 3Q. Your explanation is almost like a step-by-step tutorial, so it shouldn't be too hard, but my ETA is unknown. I think this issue could be closed for now since the initial question is positively answered.

**Comment by haf** [comment]
@buybackoff Still no time? :)

**Comment by buybackoff** [comment]
@haf, that was harder than I had expected and I was busy with [another project](https://github.com/Spreads/Spreads). For now, I am using NetMQ over LAN and for WAN I am waiting for ASP.NET's CoreCLR [version](https://github.com/aspnet/WebSockets) because they also have a client (broken now) and self-host with Kestrel, evaluating [NATS](https://github.com/nats-io/csnats) since they have TLS vs just creating SslStreams manually.
Sorry for that.

**Comment by haf** [comment]
@buybackoff No problem. Leaving issue open to track the WebSocket implementation.

**Comment by koistya** [comment]
Where can I learn more about what are the differences between Kestrel and Suave, what are the appropriate use cases for each of these two servers?

**Comment by haf** [comment]
Well, for once Suave is F# and Kestrel is C#. Suave is maintained by community. Kestrel by MSFT employees. We do PRs, MSFT creates github issues with notes from planning meetings. ;)

Also, Suave lets you use combinators to build responses:

``` fsharp
path "/hi" >=> OK "Hi there"
```

You can pre-order an intro course here https://fsharp.tv/courses/web-applications/

**Comment by buybackoff** [comment]
You say it in such a way that implies that F# is automatically better and MSFT is something bad... The reality is that Kestrel is optimized for performance, while there are many allocations and pure functional data structures in Suave (there was even a PR to replace fast imperative dict with a pure functional slow one just for functional purism and love for FP). OWIN pipe is as convenient as combinations and the fish operator, not as fancy though. Opaque steams and WebSockets work smoothly in RC2. All OWIN middleware just works (identity server, mvc). If one programs for .NET and not specifically for F#, Kestrel is stable and mature as of RC2, works well in NET451 and Core, self-hosted or using IIS/nginx. Kestrel is becoming THE server for .NET and is basically replacing IIS, which role turns into a reverse proxy.

**Comment by haf** [comment]
@buybackoff Being able to PR and make progress as a community is vastly more important than being optimized for performance. It could be argued that when some people come across a F#-native library that isn't already optimised for performance, they could contribute to it to make the world a better place. 

OWIN is not convenient when it's failing with AuthorizationException and crashing your public site, because the OWIN middleware "does it that way with exceptions", and it's absolutely not convenient that MSFT implement their own OWIN wrapper which de-factor replaces the OWIN spec, and then, to add insult to injury, re-implement those same interfaces anew inside their new ASP.Net version, further coupling and binding implementations to their own and blocking interop (which was the point of OWIN in the first place).

Opaque streams and WebSockets also work smoothly in Suave and it works well in Mono 4.3.2, .Net 4.6.1, Core (and self-hosted isn't a framework).

My 5 cents.

**Comment by isaksky** [comment]
> It could be argued that when some people who come across a F#-native library that isn't already optimised for performance, could contribute to it to rather than just dropping it, to make the world a better place.

One thing to keep in mind here that makes this a little hard:

> You have likely heard the phrase, coined by Donald Knuth, "Premature optimization is the root of all evil." This applies only to micro-optimizations at the code level. You need to understand your architecture and its constraints as you design or you will miss something crucial and severely hamstring your application. You must bake performance goals into the design up front. Performance, like security and many other aspects of software design, cannot be an afterthought, but needs to be included as an explicit goal from the start. It is not impossible to redesign an existing application from the ground up, but it is far more expensive than doing it right in the first place.

-Ben Watson - "Writing High-Performance .NET Code"

> It's absolutely not convenient that MSFT implement their own OWIN wrapper which de-factor replaces the OWIN spec, and then, to add insult to injury, re-implement those same interfaces anew inside their new ASP.Net version, further coupling and binding implementations to their own and blocking interop (which was the point of OWIN in the first place).

I noticed that too. I agree, seems pretty bizarre and bad for the community.

**Comment by buybackoff** [comment]
@haf  just do not tell me about PRs #452... 

And performance IS a (the) feature (saying to InfoQ that is is < 1 msec "on average" is not enough). I wasn't going to argue at all - I am an end user and am just giving some feedback. Suave is very nice and I have learnt a lot just by browsing through the codebase and playing with it. Such a low level of control enables to understand web requests much faster than any book!  My first comment in this thread was when Kestrel was unusable... But then **it is a pity** that so much community effort goes to a competing product and that so many users assume that F# is somehow different from .NET, instead of finally implementing something like `task{}` in addition to `async{}` at the language level. You still cross that boundary, but at the transport level.

And that thing "You can pre-order an intro course"... after it I am not sure what is your agenda. I could say that if someone needs 10+x performance boost after trying pure functional programming, just ping me...  You can pre-order a course "How to write fast code in F#"...

"PRAGMATISM AND PRODUCTIVITY ARE LOST IN THE FLAME WARS"
