### ISSUE TITLE
Should pathScan automatically url decode path segments if the segment is a string?

### ISSUE THREAD

**Issue by baronfel** [SuaveIO/suave#347]
take for example the snippet `pathScan "foo/%s" (fun path -> Suave.Http.Response.response HttpCode.HTTP_200 [||])`.

in this example, the value of 'path' could be something like "C%3A%2Fcode%2FFsAutoComplete%2FFsAutoComplete.Core%2FUtils.fs", due to the desire to pass a path segment with otherwise-invalid characters.  Right now I can easily just use one of the various url decoding mechanisms, like Uri.UnescapeDataString, but it seems like a useful quality of life enhancement.

**Comment by ademar** [comment]
Yes, I think it makes sense to UrlDecode AbsolutePath before scanning it.

**Comment by baronfel** [comment]
Do you have any preference as to which mechanism is used directly?  System.Web.HttpUtility.UrlDecode, Uri.UnescapeDataString, ...?  I'm a bit leery of System.Web.* because I don't know how cross-platform-friendly it is, especially if Sauve is hosted on OWIN/freya/libuv instead of SystemWeb directly.
For this reason I'm leaning more towards Uri.UnescapeDataString, but then we have to also do a replacement of any '+' in the segment with ' ', because this method does not replace those according to the MSDN docs.  I'd be more than happy to submit a PR with this.

**Comment by ademar** [comment]
I think we can use `System.Net.WebUtility.UrlDecode` instead.

Sure a PR with a couple of tests would be very welcome :-)

**Comment by haf** [comment]
Yes, tests. =) The two versions in .Net are each broken in different ways. We could use some Arachne code, too, perhaps?

**Comment by haf** [comment]
@baronfel Just to clarify; Suave is a web server + web parts, so while there's a potential stand-alone web part potential, we're not there. But implicit in this is that we can't host Suave on OWIN, Freya or LibUV. We have LibUV *inside* Suave in the transport, we have an OWIN module *inside* Suave, to *host* things like Freya :)

**Comment by baronfel** [comment]
@haf thanks for the clarification, it does help to properly partition the areas of responsibility for each of the projects mentioned :)  I'll hopefully be submitting a PR with tests for this soon.

**Comment by kolektiv** [comment]
As Arachne got mentioned, I've just made a change for the latest version of Arachne which actually removes the automatic encoding/decoding from percent-encoded values in parts of URIs. It turns out that although it sounds convenient, things built on top which expect the raw data (URI Templates for example) will now break in mysterious ways. In Arachne what I've done is provide different lenses in to things, so that you may work with data how you wish. As an example

```fsharp
let path_ =
        Uri.hierarchyPart_
    >-> HierarchyPart.authority_ 
    >?> snd_

let uri =
    Uri.Parse "http://www.example.com/hello%20world%21"

let val1 =
    Optic.get (path_ >?> PathAbsoluteOrEmpty.raw_) uri // returns [ "hello%20world%21" ]

let val2 =
    Optic.get (path_ >?> PathAbsoluteOrEmpty.decoded_) uri // returns [ "hello world!" ]
```

What's nice about that optic based approach is that if I want to set a new path there I can give a new unsafe string list to the second of those optics, and as `PathAbsoluteOrEmpty` is an isomorphism, the value will be automatically percent-encoded _with the correct rules for that element of a URI_. If I want to bypass that safety, I can set the value through the first optic, giving me access to the raw value.

This has just fixed (I hope) a bug in the Freya Router which uses URI Templates and had a double decoding clash in some edge cases. Now the Router uses raw values, which URI Templates deal with.

Just an opinion thrown in, magic is lovely, but it bit me... :)

**Comment by haf** [comment]
@baronfel Would you be up for a PR on this?
