### ISSUE TITLE
AutoOpen modules?

### ISSUE THREAD

**Issue by sergey-tihon** [SuaveIO/suave#369]
Pleeeease `[<AutoOpen>]` all `Suave` modules.
Spend a lot of time trying to find what is where :disappointed: 

__Is it possible ?__

I think that it is too much for simple server
```fsharp
open Suave
open Suave.Web
open Suave.Http
open Suave.Operators
open Suave.Sockets.Control
open Suave.WebSocket
open Suave.Utils
open Suave.Files
open Suave.RequestErrors
open Suave.Filters
```
would be much easier to do
```fsharp
open Suave
open Suave.Awesomeness
```

**Comment by haf** [comment]
You don't have to open Suave.Web, or Suave.Http above. Besides that I don't agree it's a big issue to open what you need. I'd be interested in hearing what you're getting from Suave.Utils though – is it the async bits?

**Comment by sergey-tihon** [comment]
`Suave.Utils` for `ASCII.bytes`.

```fsharp
let socketHandler (webSocket : WebSocket) =
  fun cx -> socket {
    while true do
      let! refreshed =
        Control.Async.AwaitEvent(refreshEvent.Publish)
        |> Suave.Sockets.SocketOp.ofAsync
      do! webSocket.send Text (ASCII.bytes "refreshed") true
  }
```

So, the idea is when you `open Fake` you can write most of automation scripts.
In the same time, when you copy Suave code sample, for example from [Tomas's post](http://tomasp.net/blog/2015/fssnip-suave/) you have no idea what to open and where to find all these functions.

![image](https://cloud.githubusercontent.com/assets/1197905/12138185/ecb35a84-b467-11e5-8909-2ceea9b9c717.png)


So rather than playing with Suave I was forced to search over Suave code base to find module names. It is really very annoying for Suave newbies like I am.

**Comment by haf** [comment]
Ah, I see. So let me explain the reason for how things are, as I see them.

When you're starting out with Suave, you want to start writing some code. Sure, you could do `open Suave` and be done, but now, how would you find the functions that you need? That you mention FAKE is funny, because I had your exact experience with it. I had no idea what the functions were called and there were no modules that could help me find them.

Instead, with Suave, without opening anything you can go "`Suave.`" and get a nice list of modules that is in part equivalent to the HTTP codes. Then you continue "`Suave.Successful.`" and you see all the functions of that module, including documentation. Now it's easy for you to find your way, because you just need to know what status code you want, or otherwise it's `request`, `context`, `Suave.Filters` or `Suave.WebSockets`.

I had a look at the post; have you tried hovering the names of the filters? Hovering shows the modules they are in. Those that don't show it are custom-made by Tomas, afaik.

Finally, we have a library reference here: https://suave.io/Suave.html, there are examples in this repo.

**Comment by haf** [comment]
Sergey, I hope the discussion above has clarified the rationales we had. I don't see this changing unless you engage in a discussion about it; we're open to change but it has to be well justified. I'm closing this issue in the meanwhile, due to it having stalled, but we can reopen if the discussion continues.
