### ISSUE TITLE
Incorrect handling of absolute request URIs

### ISSUE THREAD

**Issue by jbrestan** [SuaveIO/suave#542]
I've encountered an HTTP proxy/API gateway which sends absolute URI on the HTTP request first line. HttpBinding.uri function, which composes the full HttpRequest.uri, handles this incorrectly by gluing the whole string to the schema, host and port again, resulting in invalid URI like "http://0.0.0.0:8080/http://example.com/path/to/resource".

I was surprised the absolute URI in HTTP requests is actually valid according to RFC 2616, so I think Suave should be able to handle this case.

**Comment by jbrestan** [comment]
Added a PR to fix this case, although I'm not sure about a few things:
1) Should the resulting URI be the original absolute URI, or as it is implemented now, the binding's base URI + path from the original?
2) Can the unescaping break anything/create a security hole? Keeping things escaped broke some other tests
3) Most importantly as this is my first PR here - is this an OK way to propose a fix/extensions? :)

**Comment by haf** [comment]
1. In the app, it should be the original absolute URI because the binding is for selecting the interface, not for the logical abstraction of HTTP. But for a particular method on `HttpBinding` we want the behaviour you describe.
 2. Yes, if escaping isn't done properly we can have a security hole. The app should always read escaped data unless it queries for an unescaped URI.
 3. It's a great way to start 👍

**Comment by jbrestan** [comment]
PR is merged, closing. Thanks!
