### ISSUE TITLE
Suave doesn't work well as a subpath in IIS

### ISSUE THREAD

**Issue by rojepp** [SuaveIO/suave#562]
There are some blog posts about [hosting Suave in IIS](http://jeremyabbott.github.io/blog/2016/02-13-suave-sub-app-asking-for-help/), but it doesn't really work that well. 

The blog post above suggest to replace `path` function with a `mapSubPath` function so that you don't need to hard-code all the paths. This is not sufficient though:

* `pathScan` doesn't work in this scenario
* `Files.browseHome` doesn't work at all

I'm sure there are more scenarios, I'm a complete newb with Suave. Maybe the notion of subpath could be added into config and all built-in path related functions could handle this automatically?

**Comment by ademar** [comment]
I suspect in this case `homeFolder ` is not being set correctly. 

By default Suave will serve files from the launching folder (see https://github.com/SuaveIO/suave/blob/master/src/Suave/ParsingAndControl.fs#L170).  I figure IIS is launching Suave from System32 or similar and that is why Suave can not find your static content.

**Comment by Dzoukr** [comment]
Hi @rojepp,

to handle problems with IIS (and pathScan), you can use [Suave.IIS](https://github.com/SuaveIO/Suave.IIS).

To that problem with Files.browseHome, I will look at it. Until then, you can create your own function for serving static files on IIS:

```fsharp
let serveStatic folder request =
   let filename = request.url.Segments |> Array.last
   Files.file (folder + filename)
```
with using
```fsharp
pathRegex "(.*)\.js" >=> request (serveStatic "js/")
```

Hope it helps

**Comment by Dzoukr** [comment]
Ok, I did some investigation and problem doesn\`t seem to be `homeFolder`. The problem mentioned by @rojepp happens only if you run your Suave web app on IIS as web sub-application (not IIS Site).

Let\`s say you have `localhost/my-suave-app` as root application (using web.config). If you hit `localhost/my-suave-app/my-file.txt`, Suave correctly searches in folder where your app runs (e.g. `c:\Inetpub\wwwroot\my-suave-app`), **but** it searches for `my-suave-app\my-file.txt` instead of `my-file.txt`. This is the reason why IIS Sites works ok and sub-app don`t. Also why my ugly hack from previous comment (serverStatic function) works.

Honestly, I do not know, how to solve this now. Maybe if there would be any configuration for Suave to specify not only `homeFolder`, but also `homePath` to know where to "cut" filename & path from request. 

`Files.browseFileHome` works correctly on both, but on the other hand, you still need to specify filename.

**Comment by ademar** [comment]
> Maybe if there would be any configuration for Suave to specify not only homeFolder, but also homePath to know where to "cut" filename & path from request.

this seems like the way to go
